name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make dirs
      run: mkdir build bin  
      
    - name: make
      run: make

    - name: make test
      run: make test

    - name: run test
      run: ./bin/test
      
    
      
